name: Your New Jekyll Site
pygments: true
permalink: theme-readable.github.io/:categories/:year/:month/:day/:title 

author :
  name : Pradeep Nayak
  email : pradeep1288@gmail.com
  github : pradeep1288
  disqus_shortname: pradeepnayak
  twitter : prdpnayak